### ISSUE TITLE
Added your provider in Geocoder PHP README file

### ISSUE THREAD

**Issue by jbelien** [swisnl/geocoder-php-nationaal-georegister-provider#1]
Hello,

This is not an issue ! I just wanted to let you know I added your provider to the `README.md` file of [Geocoder PHP](https://github.com/geocoder-php/Geocoder) main repo ! :tada:

[PR #818](https://github.com/geocoder-php/Geocoder/pull/818) waiting to be merged !

**Comment by bbrala** [comment]
Nice one, thanks!
